apiVersion: batch/v1
kind: Job
metadata:
  name: quiz-portal-job
spec:
  template:
    spec:
      containers:
      - name: quiz-portal-job
        image: yash5090/quiz-portal:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
